# Generated by Django 2.2 on 2020-10-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONCEPT',
            fields=[
                ('concept_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.CharField(max_length=255)),
                ('standard_concept', models.CharField(max_length=1, null=True)),
                ('concept_code', models.CharField(max_length=50)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'CONCEPT',
            },
        ),
        migrations.CreateModel(
            name='VOCABULARY',
            fields=[
                ('vocabulary_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vocabulary_name', models.CharField(max_length=255)),
                ('vocabulary_reference', models.CharField(max_length=255)),
                ('vocabulary_version', models.CharField(max_length=255, null=True)),
                ('vocabulary_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vocabulary', to='EmrData.CONCEPT')),
            ],
            options={
                'db_table': 'VOCABULARY',
            },
        ),
        migrations.CreateModel(
            name='SOURCE_TO_CONCEPT_MAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=50)),
                ('source_vocabulary_id', models.CharField(max_length=20)),
                ('source_code_description', models.CharField(max_length=255, null=True)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
                ('source_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('target_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('target_vocabulary_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.VOCABULARY')),
            ],
            options={
                'db_table': 'SOURCE_TO_CONCEPT_MAP',
            },
        ),
        migrations.CreateModel(
            name='RELATIONSHIP',
            fields=[
                ('relationship_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('relationship_name', models.CharField(max_length=255)),
                ('is_hierarchical', models.CharField(max_length=1)),
                ('defines_ancestry', models.CharField(max_length=1)),
                ('reverse_relationship_id', models.CharField(max_length=20)),
                ('relationship_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EmrData.CONCEPT')),
            ],
            options={
                'db_table': 'RELATIONSHIP',
            },
        ),
        migrations.CreateModel(
            name='PERSON',
            fields=[
                ('person_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('year_of_birth', models.IntegerField(null=True)),
                ('month_of_birth', models.IntegerField(null=True)),
                ('day_of_birth', models.IntegerField(null=True)),
                ('birth_datetime', models.DateTimeField(null=True)),
                ('death_datetime', models.DateField(null=True)),
                ('person_source_value', models.CharField(max_length=50, null=True)),
                ('gender_source_value', models.CharField(max_length=50, null=True)),
                ('race_source_value', models.CharField(max_length=50, null=True)),
                ('ethnicity_source_value', models.CharField(max_length=50, null=True)),
                ('ethnicity_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id', 'Ethnicity'), ('standard_concept', 'S')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('ethnicity_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('gender_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id', 'Gender'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('gender_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('race_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id', 'Race'), ('standard_concept', 'S')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('race_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
            ],
            options={
                'db_table': 'PERSON',
            },
        ),
        migrations.CreateModel(
            name='DRUG_STRENGTH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_value', models.FloatField(null=True)),
                ('numerator_value', models.FloatField(null=True)),
                ('denominator_value', models.FloatField(null=True)),
                ('box_size', models.IntegerField(null=True)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
                ('amount_unit_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('denominator_unit_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('drug_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('ingredient_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('numerator_unit_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
            ],
        ),
        migrations.CreateModel(
            name='DOMAIN',
            fields=[
                ('domain_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('domain_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='domain', to='EmrData.CONCEPT')),
            ],
            options={
                'db_table': 'DOMAIN',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_SYNONYM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_synonym_name', models.CharField(max_length=1000)),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('language_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
            ],
            options={
                'db_table': 'CONCEPT_SYNONYM',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_RELATIONSHIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
                ('concept_id_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('concept_id_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('relationship_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.RELATIONSHIP')),
            ],
            options={
                'db_table': 'CONCEPT_RELATIONSHIP',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_CLASS',
            fields=[
                ('concept_class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('concept_class_name', models.CharField(max_length=255)),
                ('concept_class_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='concept_class', to='EmrData.CONCEPT')),
            ],
            options={
                'db_table': 'CONCEPT_CLASS',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_ANCESTOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_levels_of_separation', models.IntegerField()),
                ('max_levels_of_separation', models.IntegerField()),
                ('ancestor_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
                ('descendant_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.CONCEPT')),
            ],
            options={
                'db_table': 'CONCEPT_ANCESTOR',
            },
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['concept_name'], name='CONCEPT_concept_3a0e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['standard_concept'], name='CONCEPT_standar_c43a5e_idx'),
        ),
    ]
