# Generated by Django 3.1.2 on 2020-11-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CARE_SITE',
            fields=[
                ('care_site_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('care_site_name', models.CharField(max_length=255, null=True)),
                ('care_site_source_value', models.CharField(max_length=50, null=True)),
                ('place_of_service_source_value', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'CARE_SITE',
            },
        ),
        migrations.CreateModel(
            name='CDM_SOURCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdm_source_name', models.CharField(max_length=255)),
                ('cdm_source_abbreviation', models.CharField(max_length=25, null=True)),
                ('cdm_holder', models.CharField(max_length=255, null=True)),
                ('source_description', models.TextField(null=True)),
                ('source_documentation_reference', models.CharField(max_length=255, null=True)),
                ('cdm_etl_reference', models.CharField(max_length=255, null=True)),
                ('source_release_date', models.DateField(null=True)),
                ('cdm_release_date', models.DateField(null=True)),
                ('cdm_version', models.CharField(max_length=10, null=True)),
                ('vocabulary_version', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'CDM_SOURCE',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT',
            fields=[
                ('concept_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.CharField(max_length=255)),
                ('standard_concept', models.CharField(max_length=1, null=True)),
                ('concept_code', models.CharField(max_length=50)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'CONCEPT',
            },
        ),
        migrations.CreateModel(
            name='LOCATION',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(max_length=50, null=True)),
                ('address_2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip', models.CharField(max_length=9, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('location_source_value', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'LOCATION',
            },
        ),
        migrations.CreateModel(
            name='VOCABULARY',
            fields=[
                ('vocabulary_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vocabulary_name', models.CharField(max_length=255)),
                ('vocabulary_reference', models.CharField(max_length=255)),
                ('vocabulary_version', models.CharField(max_length=255, null=True)),
                ('vocabulary_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vocabulary', to='EmrData.concept')),
            ],
            options={
                'db_table': 'VOCABULARY',
            },
        ),
        migrations.CreateModel(
            name='SOURCE_TO_CONCEPT_MAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=50)),
                ('source_vocabulary_id', models.CharField(max_length=20)),
                ('source_code_description', models.CharField(max_length=255, null=True)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
                ('source_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('target_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('target_vocabulary_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.vocabulary')),
            ],
            options={
                'db_table': 'SOURCE_TO_CONCEPT_MAP',
            },
        ),
        migrations.CreateModel(
            name='RELATIONSHIP',
            fields=[
                ('relationship_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('relationship_name', models.CharField(max_length=255)),
                ('is_hierarchical', models.CharField(max_length=1)),
                ('defines_ancestry', models.CharField(max_length=1)),
                ('reverse_relationship_id', models.CharField(max_length=20)),
                ('relationship_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EmrData.concept')),
            ],
            options={
                'db_table': 'RELATIONSHIP',
            },
        ),
        migrations.CreateModel(
            name='PROVIDER',
            fields=[
                ('provider_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255, null=True)),
                ('npi', models.CharField(max_length=20, null=True)),
                ('dea', models.CharField(max_length=20, null=True)),
                ('year_of_birth', models.IntegerField(null=True)),
                ('provider_source_value', models.CharField(max_length=50, null=True)),
                ('specialty_source_value', models.CharField(max_length=50, null=True)),
                ('gender_source_value', models.CharField(max_length=50, null=True)),
                ('care_site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider', to='EmrData.care_site')),
                ('gender_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Gender'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('gender_source_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('specialty_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Provider'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('specialty_source_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'PROVIDER',
            },
        ),
        migrations.CreateModel(
            name='PERSON',
            fields=[
                ('person_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('year_of_birth', models.IntegerField(null=True)),
                ('month_of_birth', models.IntegerField(null=True)),
                ('day_of_birth', models.IntegerField(null=True)),
                ('birth_datetime', models.DateTimeField(null=True)),
                ('death_datetime', models.DateField(null=True)),
                ('person_source_value', models.CharField(max_length=50, null=True)),
                ('gender_source_value', models.CharField(max_length=50, null=True)),
                ('race_source_value', models.CharField(max_length=50, null=True)),
                ('ethnicity_source_value', models.CharField(max_length=50, null=True)),
                ('ethnicity_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Ethnicity'), ('standard_concept', 'S')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('ethnicity_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('gender_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Gender'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('gender_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('race_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Race'), ('standard_concept', 'S')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('race_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'PERSON',
            },
        ),
        migrations.CreateModel(
            name='PAYER_PLAN_PERIOD',
            fields=[
                ('payer_plan_period_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payer_plan_period_start_date', models.DateField()),
                ('payer_plan_period_end_date', models.DateField()),
                ('payer_source_value', models.CharField(max_length=50, null=True)),
                ('plan_source_value', models.CharField(max_length=50, null=True)),
                ('contract_source_value', models.CharField(max_length=50)),
                ('sponsor_source_value', models.CharField(max_length=50, null=True)),
                ('family_source_value', models.CharField(max_length=50, null=True)),
                ('stop_reason_source_value', models.CharField(max_length=50, null=True)),
                ('contract_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Relationship'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('contract_person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.person')),
                ('contract_source_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('payer_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Payer'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('payer_source_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payer_plan_period', to='EmrData.person')),
                ('plan_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Plan'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('plan_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('sponsor_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Sponsor'), ('standard_concept', 'S')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('sponsor_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='+', to='EmrData.concept')),
                ('stop_reason_concept_id', models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Plan Stop Reason'), ('standard_concept', 'S')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('stop_reason_source_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'PAYER_PLAN_PERIOD',
            },
        ),
        migrations.CreateModel(
            name='METADATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value_as_string', models.CharField(max_length=250, null=True)),
                ('metadata_date', models.DateField(null=True)),
                ('metadata_datetime', models.DateTimeField(null=True)),
                ('metadata_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('metadata_type_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('value_as_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'METADATA',
            },
        ),
        migrations.CreateModel(
            name='LOCATION_HISTORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=50)),
                ('entity_id', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='EmrData.location')),
                ('relationship_type_concept_id', models.ForeignKey(limit_choices_to=models.Q(('concept_class__concept_class_id__icontains', 'Location'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'LOCATION_HISTORY',
            },
        ),
        migrations.CreateModel(
            name='DRUG_STRENGTH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_value', models.FloatField(null=True)),
                ('numerator_value', models.FloatField(null=True)),
                ('denominator_value', models.FloatField(null=True)),
                ('box_size', models.IntegerField(null=True)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
                ('amount_unit_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('denominator_unit_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('drug_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('ingredient_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('numerator_unit_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
        ),
        migrations.CreateModel(
            name='DRUG_ERA',
            fields=[
                ('drug_era_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('drug_era_start_date', models.DateTimeField()),
                ('drug_era_end_date', models.DateTimeField()),
                ('drug_exposure_count', models.IntegerField(null=True)),
                ('gap_days', models.IntegerField(null=True)),
                ('drug_concept_id', models.ForeignKey(limit_choices_to=models.Q(domain__domain_id__icontains='Drug'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_era', to='EmrData.person')),
            ],
            options={
                'db_table': 'DRUG_ERA',
            },
        ),
        migrations.CreateModel(
            name='DOSE_ERA',
            fields=[
                ('dose_era_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dose_value', models.FloatField()),
                ('dose_era_start_date', models.DateTimeField()),
                ('dose_era_end_date', models.DateTimeField()),
                ('drug_concept_id', models.ForeignKey(limit_choices_to=models.Q(domain__domain_id__icontains='Drug'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dose_era', to='EmrData.person')),
                ('unit_concept_id', models.ForeignKey(limit_choices_to=models.Q(domain__domain_id__icontains='Unit'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'DOSE_ERA',
            },
        ),
        migrations.CreateModel(
            name='DOMAIN',
            fields=[
                ('domain_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('domain_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='domain', to='EmrData.concept')),
            ],
            options={
                'db_table': 'DOMAIN',
            },
        ),
        migrations.CreateModel(
            name='COST',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_event_id', models.BigIntegerField()),
                ('total_charge', models.FloatField(null=True)),
                ('total_cost', models.FloatField(null=True)),
                ('total_paid', models.FloatField(null=True)),
                ('paid_by_payer', models.FloatField(null=True)),
                ('paid_by_patient', models.FloatField(null=True)),
                ('paid_patient_copay', models.FloatField(null=True)),
                ('paid_patient_coinsurance', models.FloatField(null=True)),
                ('paid_patient_deductible', models.FloatField(null=True)),
                ('paid_by_primary', models.FloatField(null=True)),
                ('paid_ingredient_cost', models.FloatField(null=True)),
                ('paid_dispensing_fee', models.FloatField(null=True)),
                ('payer_plan_period_id', models.BigIntegerField(null=True)),
                ('amount_allowed', models.FloatField(null=True)),
                ('revenue_code_source_value', models.CharField(max_length=50, null=True)),
                ('drg_source_value', models.CharField(max_length=3, null=True)),
                ('cost_domain_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.domain')),
                ('cost_type_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('currency_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('drg_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('revenue_code_concept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'COST',
            },
        ),
        migrations.CreateModel(
            name='CONDITION_ERA',
            fields=[
                ('condition_era_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_era_start_date', models.DateTimeField()),
                ('condition_era_end_date', models.DateTimeField()),
                ('condition_occurrence_count', models.IntegerField(null=True)),
                ('condition_concept_id', models.ForeignKey(limit_choices_to=models.Q(domain__domain_id__icontains='Condition'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='condition_era', to='EmrData.person')),
            ],
            options={
                'db_table': 'CONDITION_ERA',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_SYNONYM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_synonym_name', models.CharField(max_length=1000)),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('language_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'CONCEPT_SYNONYM',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_RELATIONSHIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(max_length=1, null=True)),
                ('concept_id_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('concept_id_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('relationship_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.relationship')),
            ],
            options={
                'db_table': 'CONCEPT_RELATIONSHIP',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_CLASS',
            fields=[
                ('concept_class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('concept_class_name', models.CharField(max_length=255)),
                ('concept_class_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='concept_class', to='EmrData.concept')),
            ],
            options={
                'db_table': 'CONCEPT_CLASS',
            },
        ),
        migrations.CreateModel(
            name='CONCEPT_ANCESTOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_levels_of_separation', models.IntegerField()),
                ('max_levels_of_separation', models.IntegerField()),
                ('ancestor_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
                ('descendant_concept_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept')),
            ],
            options={
                'db_table': 'CONCEPT_ANCESTOR',
            },
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['concept_name'], name='CONCEPT_concept_3a0e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['standard_concept'], name='CONCEPT_standar_c43a5e_idx'),
        ),
        migrations.AddField(
            model_name='care_site',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EmrData.location'),
        ),
        migrations.AddField(
            model_name='care_site',
            name='place_of_service_concept_id',
            field=models.ForeignKey(limit_choices_to=models.Q(('domain__domain_id__icontains', 'Visit'), ('standard_concept', 'S')), on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EmrData.concept'),
        ),
    ]
